version: '3.4'

services:
  mybank.web:
    container_name: mybankweb
    image: ${DOCKER_REGISTRY-}mybankweb
    build:
      context: .
      dockerfile: MyBank.Web/Dockerfile
    ports:
      - "8080:80"
      - "80"
      - "443"
      
    depends_on: 
        - "mybank.db"
    networks:
        - mybanknetwork

  mybank.db:
    container_name: mybankdb
    image: mariadb:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: mybank
        MYSQL_DATABASE: mybank
    expose:
        - "3306"
    ports:
        - "3301:3306"
    networks:
        - mybanknetwork

networks:
    mybanknetwork: