version: '3.4'

services:
  mybank.web:
    container_name: mybankweb
    image: ${DOCKER_REGISTRY-}mybankweb
    build:
      context: .
      dockerfile: MyBank.Web/Dockerfile
      networks:
            - mybanknetwork
  mybank.db:
    container_name: mybankdb
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_USER: mybank
            MYSQL_ROOT_PASSWORD: mybank
            MYSQL_DATABASE: mybank
        expose:
              - "3306"
        ports:
            - "3301:3306"
        networks:
            -  minhasnfcnetwork

networks:
    mybanknetwork: